[window]
padding = { x = 16, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 0.3
blur = false
[scrolling]
history = 2000
multiplier = 1

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = 'FiraCode Nerd Font Mono'
style = "Regular"

[mouse]
hide_when_typing = true

[keyboard]
