[window]
padding = { x = 16, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 0.3
blur = false
[scrolling]
history = 2000
multiplier = 1
[font]
normal.family = "MonaspiceArNerdFontMono"
normal.style = "Light"
italic.family = "MonaspiceXeNerdFontMono"
italic.style = "LightItalic"
bold.family = "MonaspiceKrNerdFontMono"
bold.style = "Bold"
bold_italic.family = "MonaspiceKrNerdFontMono"
bold_italic.style = "BoldItalic"
size = 15
[mouse]
hide_when_typing = true
[keyboard]
