[window]
padding = { x = 16, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 0.3
blur = false
[scrolling]
history = 2000
multiplier = 1
[font]
#normal = { family = "alacritty", style = "Regular" }
size = 14
[mouse]
hide_when_typing = true
[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
