[helpers]

[default]
depends = []

[default.files]
#Kvantum = "~/.config/Kvantum"
#ags = "~/.config/ags"
alacritty = "~/.config/alacritty"
#btop = "~/.config/btop"
#cava = "~/.config/cava"
#dconf = "~/.config/dconf"
#fastfetch = "~/.config/fastfetch"
#"gtk-3.0" = "~/.config/gtk-3.0"
hypr = "~/.config/hypr"
nvim = "~/.config/nvim"
#nwg-look = "~/.config/nwg-look"
#qt5ct = "~/.config/qt5ct"
#qt6ct = "~/.config/qt6ct"
#rofi = "~/.config/rofi"
#simple-update-notifier = "~/.config/simple-update-notifier"
#swappy = "~/.config/swappy"
#swaync = "~/.config/swaync"
#systemd = "~/.config/systemd"
#vesktop = "~/.config/vesktop"
#wallust = "~/.config/wallust"
#waybar = "~/.config/waybar"
wezterm = "~/.config/wezterm"
#wlogout = "~/.config/wlogout"
#xfce4 = "~/.config/xfce4"
#yay = "~/.config/yay"
yazi = "~/.config/yazi"

[default.variables]

[settings]
default_target_type = "symbolic"
